name: Empaquetado Automático

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Comprimir y Empaquetar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comprimir proyecto en ZIP
        run: |
          zip -r proyecto-html.zip . -x ".git*" ".github*"

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: codigo-unificado-html
          path: proyecto-html.zip